const sampleMagazines = [
{ title: "Tejas Vol 1",
  smallDescription: "We start by gaining a deep  understanding of your business goals.",
  bookLink:"https://online.pubhtml5.com/hiwar/abef/",
  image:{
    fileName: "TejadVol1.jpg",
    url: "http://localhost:5173/src/components/asset/1.avif",
  },
  views:0,
  optionDate: 2023,
  latest:"yes",
  },
  { title: "Tejas Vol 2",
    smallDescription: "Next, our team of experts develops tailored solutions.",
    bookLink:"	http://localhost:5173/src/components/asset/2.avif",
    image:{
      fileName: "TejadVol1.jpg",
      url: "http://localhost:5173/src/components/asset/1.avif",
    },
    views:0,
    optionDate: 2023,
    latest:"yes",
    },{ title: "Tejas Vol 3.1",
      smallDescription: "We leverage cutting-edge technology to implement seamlessly.",
      bookLink:"https://online.pubhtml5.com/hiwar/abef/",
      image:{
        fileName: "TejadVol1.jpg",
        url: "http://localhost:5173/src/components/asset/1.avif",
      },
      views:0,
      optionDate: 2023,
      },{ title: "Tejas Vol 3.1",
        smallDescription: "We leverage cutting-edge technology to implement seamlessly.",
        bookLink:"https://online.pubhtml5.com/hiwar/abef/",
        image:{
          fileName: "TejadVol1.jpg",
          url: "http://localhost:5173/src/components/asset/1.avif",
        },
        views:0,
        optionDate: 2023,
        latest:"yes",
        },{ title: "Tejas Vol 3.1",
          smallDescription: "We leverage cutting-edge technology to implement seamlessly.",
          bookLink:"https://online.pubhtml5.com/hiwar/abef/",
          image:{
            fileName: "TejadVol1.jpg",
            url: "http://localhost:5173/src/components/asset/1.avif",
          },
          views:0,
          optionDate: 2023,
          },{ title: "Tejas Vol 3.1",
            smallDescription: "We leverage cutting-edge technology to implement seamlessly.",
            bookLink:"https://online.pubhtml5.com/hiwar/abef/",
            image:{
              fileName: "TejadVol1.jpg",
              url: "http://localhost:5173/src/components/asset/1.avif",
            },
            views:0,
            optionDate: 2023,
            }];
module.exports = { data: sampleMagazines};
